/**
 * Reads Supabase URL + anon key from `globalThis.__ONETAP_SUPABASE__`, set by
 * `pages/supabase-env.js` (and a copy in `js/`) — generated by `npm run build` / inject-env.mjs.
 *
 * Every app page must include `<script src="supabase-env.js"></script>` in `<head>`
 * *before* any `<script type="module">` that imports the Supabase client.
 *
 * The anon key is public by design (RLS protects data); never commit a service-role key.
 */
const b = typeof globalThis !== 'undefined' ? globalThis.__ONETAP_SUPABASE__ : null;
const url = b && typeof b.url === 'string' ? b.url.trim() : '';
const key = b && typeof b.key === 'string' ? b.key.trim() : '';

export const SUPABASE_URL = url;
export const SUPABASE_ANON_KEY = key;
