#!/usr/bin/env node
/**
 * Writes supabase/runtime-config.js from environment variables (Vercel / CI).
 * Uses VITE_* names so the same vars work if you later add Vite.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const target = path.join(root, 'supabase', 'runtime-config.js');

const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '';
const key = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || '';

if (url && key) {
  const body = `/**
 * Auto-generated by scripts/inject-env.mjs — do not commit real values.
 * Regenerated on each deploy when env vars are set.
 */
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;
  fs.writeFileSync(target, body, 'utf8');
  process.stdout.write(`inject-env: wrote ${path.relative(root, target)}\n`);
} else {
  process.stdout.write(
    'inject-env: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY not set — keeping existing supabase/runtime-config.js\n',
  );
}
