#!/usr/bin/env node
/**
 * Writes supabase/runtime-config.js from environment variables (Vercel / CI / local).
 * Uses VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (aliases: SUPABASE_URL, SUPABASE_ANON_KEY).
 * Loads optional root .env so `npm run build` works locally without exporting vars.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const target = path.join(root, 'supabase', 'runtime-config.js');
const envPath = path.join(root, '.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  const text = fs.readFileSync(filePath, 'utf8');
  for (let line of text.split(/\n')) {
    line = line.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function pickUrl(fileEnv) {
  return (
    process.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    fileEnv.VITE_SUPABASE_URL ||
    fileEnv.SUPABASE_URL ||
    ''
  ).trim();
}

function pickKey(fileEnv) {
  return (
    process.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_ANON_KEY ||
    fileEnv.VITE_SUPABASE_ANON_KEY ||
    fileEnv.SUPABASE_ANON_KEY ||
    ''
  ).trim();
}

function looksPlaceholder(url, key) {
  if (!url || !key) return true;
  if (url.includes('YOUR_PROJECT_REF') || url.includes('xxxxx')) return true;
  if (key === 'YOUR_SUPABASE_ANON_KEY' || key === 'your_anon_key_here') return true;
  if (key.length < 32) return true;
  try {
    const u = new URL(url);
    if (u.protocol !== 'https:' || !u.hostname) return true;
  } catch {
    return true;
  }
  return false;
}

const fileEnv = parseEnvFile(envPath);
const url = pickUrl(fileEnv);
const key = pickKey(fileEnv);
const onVercel = process.env.VERCEL === '1';

if (onVercel && (!url || !key || looksPlaceholder(url, key))) {
  console.error(
    'inject-env: missing or invalid Supabase credentials.\n' +
      'Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel → Settings → Environment Variables\n' +
      '(Production and Preview), then redeploy. They must be available at build time.\n' +
      (onVercel ? `VERCEL_ENV=${process.env.VERCEL_ENV || '?'}\n` : ''),
  );
  process.exit(1);
}

if (url && key && !looksPlaceholder(url, key)) {
  const body = `/**
 * Auto-generated by scripts/inject-env.mjs from VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY (or .env).
 * Do not commit real secrets to a public repository.
 */
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;
  fs.writeFileSync(target, body, 'utf8');
  const written = fs.readFileSync(target, 'utf8');
  if (written.includes('YOUR_PROJECT_REF') || written.includes('YOUR_SUPABASE_ANON_KEY')) {
    console.error('inject-env: internal error — written file still contains placeholders.');
    process.exit(1);
  }
  process.stdout.write(`inject-env: wrote ${path.relative(root, target)} with live Supabase URL + anon key.\n`);
} else {
  process.stderr.write(
    '\n[inject-env] WARNING: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are missing or invalid.\n' +
      '  supabase/runtime-config.js was not updated. Login/signup will fail until you run a successful build with real env vars.\n' +
      '  Local: copy .env.example → .env, fill values, run npm run build.\n\n',
  );
}
