#!/usr/bin/env node
/**
 * Writes Supabase URL + anon key into boot scripts (globalThis.__ONETAP_SUPABASE__).
 * Uses VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY (aliases SUPABASE_*). Reads root `.env`.
 *
 * Writes TWO copies so production works even if hosting only exposes certain trees:
 *   • pages/supabase-env.js — loaded as <script src="supabase-env.js"> from pages/*.html
 *   • js/supabase-env.js      — available at /js/supabase-env.js when the full repo is deployed
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const OUTPUT_PATHS = [
  path.join(root, 'pages', 'supabase-env.js'),
  path.join(root, 'js', 'supabase-env.js'),
];
const envPath = path.join(root, '.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  let text = fs.readFileSync(filePath, 'utf8');
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
  for (let line of text.split(/\n')) {
    line = line.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function normalizeSecret(s) {
  return String(s || '')
    .trim()
    .replace(/^\uFEFF/, '')
    .replace(/\r\n/g, '')
    .replace(/\n/g, '')
    .trim();
}

function pickUrl(fileEnv) {
  return normalizeSecret(
    process.env.VITE_SUPABASE_URL ||
      process.env.SUPABASE_URL ||
      fileEnv.VITE_SUPABASE_URL ||
      fileEnv.SUPABASE_URL ||
      '',
  );
}

function pickKey(fileEnv) {
  return normalizeSecret(
    process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      fileEnv.VITE_SUPABASE_ANON_KEY ||
      fileEnv.SUPABASE_ANON_KEY ||
      '',
  );
}

function looksPlaceholder(url, key) {
  if (!url || !key) return true;
  if (url.includes('YOUR_PROJECT_REF') || url.includes('xxxxx')) return true;
  if (key === 'YOUR_SUPABASE_ANON_KEY' || key === 'your_anon_key_here') return true;
  if (key.length < 20) return true;
  try {
    const u = new URL(url);
    if (u.protocol !== 'https:' || !u.hostname) return true;
  } catch {
    return true;
  }
  return false;
}

function writeAllOutputs(body) {
  for (const p of OUTPUT_PATHS) {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, body, 'utf8');
  }
}

function assertOutputs(label) {
  for (const p of OUTPUT_PATHS) {
    if (!fs.existsSync(p)) {
      console.error(`inject-env: ${label} — missing output:`, path.relative(root, p));
      process.exit(1);
    }
    if (fs.readFileSync(p, 'utf8').length < 40) {
      console.error(`inject-env: ${label} — output too small:`, path.relative(root, p));
      process.exit(1);
    }
  }
}

const fileEnv = parseEnvFile(envPath);
const url = pickUrl(fileEnv);
const key = pickKey(fileEnv);

const onVercel = process.env.VERCEL === '1';
const strictHost =
  onVercel ||
  process.env.CI === 'true' ||
  process.env.NETLIFY === 'true' ||
  process.env.CF_PAGES === '1';

if (strictHost && (!url || !key || looksPlaceholder(url, key))) {
  console.error(
    'inject-env: missing or invalid Supabase credentials.\n' +
      'Set these in your host’s dashboard (build-time environment variables):\n' +
      '  • VITE_SUPABASE_URL  — Supabase → Project Settings → API → Project URL (https://….supabase.co)\n' +
      '  • VITE_SUPABASE_ANON_KEY — same page → Project API keys → anon public\n' +
      'Vercel: Project → Settings → Environment Variables → add both for Production and Preview, then Redeploy.\n' +
      (onVercel ? `VERCEL_ENV=${process.env.VERCEL_ENV || '?'}\n` : ''),
  );
  process.exit(1);
}

if (url && key && !looksPlaceholder(url, key)) {
  const payload = JSON.stringify({ url, key });
  const body = `/* Generated by scripts/inject-env.mjs — do not edit by hand */
(function(){'use strict';
try{globalThis.__ONETAP_SUPABASE__=Object.freeze(${payload});}catch(e){globalThis.__ONETAP_SUPABASE__=null;}
})();
`;
  writeAllOutputs(body);
  assertOutputs('after credentials write');
  const sample = fs.readFileSync(OUTPUT_PATHS[0], 'utf8');
  if (sample.includes('YOUR_PROJECT_REF') || sample.includes('YOUR_SUPABASE_ANON_KEY')) {
    console.error('inject-env: internal error — output still contains placeholders.');
    process.exit(1);
  }
  process.stdout.write(
    `inject-env: wrote pages/supabase-env.js + js/supabase-env.js (host ${new URL(url).hostname}, key length ${key.length}).\n`,
  );
} else {
  const body = `/* No credentials: run npm run build with VITE_SUPABASE_* or a filled root .env */
(function(){'use strict';try{globalThis.__ONETAP_SUPABASE__=null;}catch(e){}})();
`;
  writeAllOutputs(body);
  assertOutputs('after null stub write');
  process.stderr.write(
    '\n[inject-env] WARNING: no valid VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY — wrote null stubs.\n' +
      '  Login will fail until you add a root .env or export vars and run npm run build again.\n\n',
  );
}
